<a href="https://colab.research.google.com/github/kekubhai/Build-/blob/main/BasicCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

torch.manual_seed(42)
np.random.seed(42)

In [11]:
print("=" * 60)
print("CONVOLUTIONAL NEURAL NETWORK - LAYER IMPLEMENTATIONS")
print("=" * 60)

# ============================================================================
# 1. BASIC CONVOLUTION OPERATION
# ============================================================================
print("\n" + "=" * 60)
print("1. BASIC CONVOLUTION OPERATION")
print("=" * 60)
image_6x6 = torch.tensor([
    [3, 0, 1, 2, 7, 4],
    [1, 5, 8, 9, 3, 1],
    [2, 7, 2, 5, 1, 3],
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
], dtype=torch.float32)

print(f"Original 6x6 image:\n{image_6x6}")
print(f"Shape: {image_6x6.shape}")

# Reshape for PyTorch conv2d: (batch, channels, height, width)
image_tensor = image_6x6.unsqueeze(0).unsqueeze(0)
print(f"Tensor shape for conv2d: {image_tensor.shape}")


# Vertical edge detection filter (Sobel-like)
vertical_filter = torch.tensor([[
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
]], dtype=torch.float32).unsqueeze(0)  # (1, 1, 3, 3)

print(f"\nVertical edge detection filter (3x3):\n{vertical_filter.squeeze()}")
conv_output = F.conv2d(image_tensor, vertical_filter, stride=1, padding=0)
print(f"\nConvolution result (4x4):\n{conv_output.squeeze()}")
print(f"Output shape: {conv_output.shape}")

CONVOLUTIONAL NEURAL NETWORK - LAYER IMPLEMENTATIONS

1. BASIC CONVOLUTION OPERATION
Original 6x6 image:
tensor([[3., 0., 1., 2., 7., 4.],
        [1., 5., 8., 9., 3., 1.],
        [2., 7., 2., 5., 1., 3.],
        [0., 1., 3., 1., 7., 8.],
        [4., 2., 1., 6., 2., 8.],
        [2., 4., 5., 2., 3., 9.]])
Shape: torch.Size([6, 6])
Tensor shape for conv2d: torch.Size([1, 1, 6, 6])

Vertical edge detection filter (3x3):
tensor([[ 1.,  0., -1.],
        [ 1.,  0., -1.],
        [ 1.,  0., -1.]])

Convolution result (4x4):
tensor([[ -5.,  -4.,   0.,   8.],
        [-10.,  -2.,   2.,   3.],
        [  0.,  -2.,  -4.,  -7.],
        [ -3.,  -2.,  -3., -16.]])
Output shape: torch.Size([1, 1, 4, 4])


In [12]:
print("\n" + "=" * 60)
print("2. EDGE DETECTION DEMONSTRATION")
print("=" * 60)

# Create an image with clear vertical edge (light left, dark right)
image_vertical_edge = torch.zeros(6, 6)
image_vertical_edge[:, :3] = 10  # Left half bright
image_vertical_edge[:, 3:] = 0   # Right half dark
print(f"Image with vertical edge (light→dark):\n{image_vertical_edge}")



2. EDGE DETECTION DEMONSTRATION
Image with vertical edge (light→dark):
tensor([[10., 10., 10.,  0.,  0.,  0.],
        [10., 10., 10.,  0.,  0.,  0.],
        [10., 10., 10.,  0.,  0.,  0.],
        [10., 10., 10.,  0.,  0.,  0.],
        [10., 10., 10.,  0.,  0.,  0.],
        [10., 10., 10.,  0.,  0.,  0.]])
